# Generated by Django 5.1.2 on 2024-10-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='ammount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
